[package]
name = "rustics"
version = "0.1.0"
edition = "2021"
crate-type = ["dylib"]


[lib]
name = "rustics"
crate-type = ["dylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
